In [1]:
import numpy as np

In [3]:
# vectorize 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Add:",  arr1 + arr2)

Add: [11 22 33 44 55]


In [5]:
lst1= [1,2,3,4,5]
lst2 = [10,20,30,40,50]
lst1+lst2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [8]:
## Universal Fuction
arr = np.array([2,3,4,5,6])
# square root
print("Sq root",np.sqrt(arr))
print("Exponential",np.exp(arr))
print("Sine",np.sin(arr))
print("Natural log",np.log(arr))


Sq root [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural log [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
## Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print("Shape of array :",arr.shape)
print("Row :",arr.shape[0])
print("Column :",arr.shape[1])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array : (3, 4)
Row : 3
Column : 4


In [17]:
print("item on index arr[0][0]:", arr[0][0])

item on index arr[0][0]: 1


In [22]:
# find out 7,8,11,12
print(arr[1:,2:])

array([[ 7,  8],
       [11, 12]])

In [23]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# find out 6,7,10,11
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [32]:
### Normalisation, it means data mean is 0 and stdv 1
data = np.array([1,2,3,4,5])
print("Raw_data :", data)
mean = data.mean()
st_dev = data.std()

normalised = (data-mean)/st_dev
print("Normalised Data :", normalised)

Raw_data : [1 2 3 4 5]
Normalised Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
## Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data)
print(data>5)
print(data[data>5])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [35]:
# Multiple operations
print(data[(data>5) & (data != 10)])

[6 7 8 9]
